name: Make Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-16.04
    env:
      BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: sumneko/vscode-lua
          ref: v0.20.6
          submodules: recursive
      # - uses: actions/checkout@v2
      #   with:
      #     repository: sublimelsp/LSP-lua
      #     ref: v0.20.6
      - uses: jfrog/setup-jfrog-cli@v1
      - run: jfrog --version
      - run: jfrog bt package-show --user rwols --key $BINTRAY_API_KEY rwols/LSP-lua/linux
